version: 0.2

phases:
  build:
      commands:
        - echo Build started on `date`
        - echo copy everything to s3 bucket
        - aws s3 cp . s3://sgdpr-deploymentstore/ --recursive
        - echo finished copying files to s3 sgdpr-deploymentstore