version: 0.2

phases:
 pre_build:
    commands:
     - echo Entered the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
      commands:
        - echo Build started on `date`
        - echo copy everything to s3 bucket
        - aws s3 cp . s3://sgdpr-deploymentstore/ --recursive
        - echo finished copying files to s3 sgdpr-deploymentstore